baseURL = "https://dev-sec.io/"
languageCode = "en-us"
title = "DevSec Hardening Framework"
theme = "devsec"
metaDataFormat = "yaml"

[[menu.global]]
  name = "Baselines"
  weight = 1
  identifier = "baselines"
  url = "/baselines/"

[[menu.global]]
  name = "Articles"
  weight = 2
  identifier = "articles"
  url = "/articles/"

[[menu.global]]
  name = "Blog"
  weight = 3
  identifier = "blog"
  url = "/blog/"

[[menu.global]]
  name = "Contributing"
  weight = 4
  identifier = "contributing"
  url = "/contributing/"

[[menu.global]]
  name = "Community"
  weight = 4
  identifier = "comunity"
  url = "/community/"

[[menu.global]]
  name = "GitHub"
  weight = 5
  identifier = "github"
  url = "https://github.com/dev-sec"
